### ISSUE TITLE
[AdminPortClient] Error while processing msg

### ISSUE THREAD

**Issue by shoter** [shoter/OpenTTDAdminPort#14]
```
[ERROR][06/04/2023 19:32:02.829Z][Thread 0016][akka://AdminPortClient/user/Main] The given key '5' was not present in the dictionary.
Cause: System.Collections.Generic.KeyNotFoundException: The given key '5' was not present in the dictionary.
   at System.Collections.Generic.Dictionary`2.get_Item(TKey key)
   at OpenTTDAdminPort.MainActor.AdminPortClientActor.ProcessAdminMessage(ConnectedData data, IAdminMessage message)
   at OpenTTDAdminPort.MainActor.AdminPortClientActor.<ConnectedState>b__23_1(Event`1 state)
   at Akka.Actor.FSM`2.ProcessEvent(Event`1 fsmEvent, Object source)
   at Akka.Actor.FSM`2.ProcessMsg(Object any, Object source)
   at Akka.Actor.FSM`2.Receive(Object message)
   at Akka.Actor.ActorBase.AroundReceive(Receive receive, Object message)
   at Akka.Actor.ActorCell.ReceiveMessage(Object message)
   at Akka.Actor.ActorCell.Invoke(Envelope envelope)
[INFO][06/04/2023 19:32:02.866Z][Thread 0031][akka://AdminPortClient/user/Main/tcp0] Message [KeyNotFoundException] from [akka://AdminPortClient/user/Main#27813560] to [akka://AdminPortClient/user/Main/tcp0#1537265379] was not delivered. [1] dead letters encountered. If this is not an expected behavior then [akka://AdminPortClient/user/Main/tcp0#1537265379] may have terminated unexpectedly. This logging can be turned off or adjusted with configuration settings 'akka.log-dead-letters' and 'akka.log-dead-letters-during-shutdown'. Message content: System.Collections.Generic.KeyNotFoundException: The given key '5' was not present in the dictionary.
   at System.Collections.Generic.Dictionary`2.get_Item(TKey key)
   at OpenTTDAdminPort.MainActor.AdminPortClientActor.ProcessAdminMessage(ConnectedData data, IAdminMessage message)
   at OpenTTDAdminPort.MainActor.AdminPortClientActor.<ConnectedState>b__23_1(Event`1 state)
   at Akka.Actor.FSM`2.ProcessEvent(Event`1 fsmEvent, Object source)
   at Akka.Actor.FSM`2.ProcessMsg(Object any, Object source)
   at Akka.Actor.FSM`2.Receive(Object message)
   at Akka.Actor.ActorBase.AroundReceive(Receive receive, Object message)
   at Akka.Actor.ActorCell.ReceiveMessage(Object message)
   at Akka.Actor.ActorCell.Invoke(Envelope envelope)
```

**Comment by shoter** [comment]
Last changes will make it easier to know which message is responsible for such error

**Comment by shoter** [comment]
#18 resolves that - probably.
